apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
  labels:
    app: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris
        image: vzaigrin/iris:latest
        ports:
        - containerPort: 5000