apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    app: iris
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: iris
  type: LoadBalancer
  selector:
    app: iris